"""APEX ULTRA - W47.2: compression-breakout replay (Phase 47, OFFLINE).

A deterministic, single-pass research replay of the volatility-compression
breakout strategy pre-registered in docs/PHASE_47_BOUNDARY_AGREEMENT.md.

This is NOT a reusable strategy component and deliberately imports nothing
from engine/. Its state (episode lifecycle, frozen range, expiry window,
one-position suppression, frozen ATR, MAE/MFE collection) is specific to
this research protocol. Promotion into engine/strategy/ would be a
separate phase that must earn the right to touch the frozen engine.

PRE-REGISTERED CONFIGURATION (Section C of the agreement):
    compression metric  ATR(14) percentile
    lookback            96 bars (24 hours)
    threshold           percentile < 0.20 (strict)
    entry               first CLOSE beyond the frozen episode range
    expiry              4 bars after the episode ends
    initial stop        1.5 x ATR(14) frozen at entry
    trail               3.0 x ATR(14), inactive until +1R, ratchets only
    position policy     one at a time, no pyramiding

IMPLEMENTATION DECISIONS recorded during protocol review, so that no
silent choice is left to the code:

  Percentile (inclusive rank, no interpolation):
      p_t = count(ATR_i <= ATR_t) / 96
  over the trailing 96 ATR values INCLUDING the current one. Qualifies
  when p_t < 0.20. Because the current value is included, the minimum
  attainable percentile is 1/96 ~= 1.04%, never 0. That is expected
  behaviour, not a defect.

  Warmup: ATR(14) needs 14 bars; the percentile window needs 96 ATR
  values. The first evaluable bar index is 14 + 96 - 1 = 109. No episode
  may begin during warmup and warmup bars are excluded from all
  statistics.

  Execution is CLOSE-ONLY, exactly as the agreement mandates. Entries at
  breakout-bar close; stop and trail evaluated on subsequent bar closes
  only; exit at the first close beyond the active stop. NO intrabar
  fills are simulated.

      KNOWN BIAS, to be disclosed by W47.3: a bar whose low pierces the
      stop but whose close recovers above it does NOT exit here, whereas
      a resting stop order in live trading would have been filled. With
      a tight initial stop and a wide trail this likely biases measured
      expectancy UPWARD relative to live execution. This is not neutral
      conservatism and must not be presented as such.

  MAE/MFE are measured from intrabar highs and lows. These are
  MEASUREMENTS, not execution decisions, so using extremes here does not
  violate close-only execution.

  The full year is replayed in ONE continuous walk. The in-sample /
  holdout split is applied later, in W47.3, by ENTRY timestamp. Splitting
  during replay would reset state at the boundary, discard open
  positions, truncate active episodes, and produce a holdout not
  generated by the same process as the in-sample trades.

Usage (from the repo root):
    py -m tools.backtest_compression_breakout
    py -m tools.backtest_compression_breakout --stop-atr 2.5   (Appendix X)

Any parameter deviation from the pre-registered defaults triggers a loud
warning and is recorded in summary.json, so an exploratory run can never
be mistaken for the primary configuration.
"""
from __future__ import annotations

import argparse
import csv
import glob
import hashlib
import json
import sys
from collections import deque
from pathlib import Path

# --- pre-registered defaults (Section C) --------------------------------
DEF_ATR_PERIOD = 14
DEF_LOOKBACK = 96
DEF_THRESHOLD = 0.20
DEF_STOP_ATR = 1.5
DEF_TRAIL_ATR = 3.0
DEF_TRAIL_ACTIVATE_R = 1.0
DEF_EXPIRY_BARS = 4

SYMBOL = "cryBTCUSD"
GRANULARITY = 900
OUTPUT_DIR = Path("engine") / "output"
CANDLE_GLOB = str(OUTPUT_DIR / f"candles_{SYMBOL}_{GRANULARITY}_*.jsonl")


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_candles() -> tuple:
    paths = sorted(glob.glob(CANDLE_GLOB))
    if not paths:
        sys.exit(f"BLOCKED: no candle file matching {CANDLE_GLOB}. "
                 "Run tools/fetch_candles.py --symbol cryBTCUSD first.")
    path = Path(paths[-1])
    rows = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            k = json.loads(line)
            rows.append((int(k["epoch"]), float(k["open"]), float(k["high"]),
                         float(k["low"]), float(k["close"])))
    rows.sort(key=lambda r: r[0])
    print(f"loaded {len(rows)} candles from {path}")
    return rows, path


def _wilder_atr(rows: list, period: int) -> list:
    """Return a list the same length as rows; entries are None until ATR
    is defined. Wilder smoothing, seeded with the simple mean of the
    first `period` true ranges."""
    atr = [None] * len(rows)
    trs = []
    for i in range(1, len(rows)):
        _, _, h, l, _ = rows[i]
        prev_close = rows[i - 1][4]
        tr = max(h - l, abs(h - prev_close), abs(l - prev_close))
        trs.append(tr)
        idx = len(trs)
        if idx == period:
            atr[i] = sum(trs) / period
        elif idx > period:
            atr[i] = (atr[i - 1] * (period - 1) + tr) / period
    return atr


def run(args) -> int:
    rows, candle_path = _load_candles()
    n = len(rows)

    defaults = {
        "atr_period": DEF_ATR_PERIOD, "lookback": DEF_LOOKBACK,
        "threshold": DEF_THRESHOLD, "stop_atr": DEF_STOP_ATR,
        "trail_atr": DEF_TRAIL_ATR, "trail_activate_r": DEF_TRAIL_ACTIVATE_R,
        "expiry_bars": DEF_EXPIRY_BARS,
    }
    params = {
        "atr_period": args.atr_period, "lookback": args.lookback,
        "threshold": args.threshold, "stop_atr": args.stop_atr,
        "trail_atr": args.trail_atr, "trail_activate_r": args.trail_activate_r,
        "expiry_bars": args.expiry_bars,
    }
    deviations = [k for k in defaults if defaults[k] != params[k]]
    prereg_match = not deviations

    print("=" * 68)
    print("W47.2 - COMPRESSION BREAKOUT REPLAY")
    print("=" * 68)
    for k, v in params.items():
        mark = "  <-- DEVIATION" if k in deviations else ""
        print(f"  {k:20s}: {v}{mark}")
    if deviations:
        print()
        print("!" * 68)
        print("!! EXPLORATORY RUN - parameters deviate from the pre-registered")
        print("!! configuration. Per the agreement (Appendix X) this run CANNOT")
        print("!! produce a pass, a partial pass, or any claim about the")
        print("!! hypothesis. Its only output is a candidate hypothesis for a")
        print("!! future phase with fresh data.")
        print("!! Deviating fields: " + ", ".join(deviations))
        print("!" * 68)
    print()

    atr = _wilder_atr(rows, params["atr_period"])
    first_evaluable = params["atr_period"] + params["lookback"] - 1
    warmup_bars = min(first_evaluable, n)
    print(f"total bars {n}, warmup {warmup_bars}, evaluable {max(0, n - warmup_bars)}")

    window: deque = deque(maxlen=params["lookback"])
    for i in range(n):
        if atr[i] is not None:
            window.append(atr[i])
        if i >= first_evaluable:
            break

    # --- state ----------------------------------------------------------
    ep_state = "inactive"          # inactive | active | frozen
    ep_high = ep_low = None
    ep_bars = 0
    expiry_left = 0

    pos = None                     # None | dict
    trades = []
    events = []

    episodes_started = 0
    episodes_expired = 0
    episodes_consumed = 0
    ignored_signals = 0

    def log(i, msg):
        events.append(f"{rows[i][0]}\t{i}\t{msg}")

    for i in range(n):
        epoch, o, h, l, c = rows[i]

        if atr[i] is None:
            continue
        if i > first_evaluable:
            window.append(atr[i])
        if i < first_evaluable:
            continue

        # ---- percentile (inclusive rank, current value included) -------
        cur = atr[i]
        vals = list(window)
        pct = sum(1 for v in vals if v <= cur) / len(vals)
        qualifies = pct < params["threshold"]

        # ---- manage an open position FIRST (close-only evaluation) -----
        if pos is not None:
            pos["bars_held"] += 1
            # MAE / MFE from intrabar extremes (measurement, not execution)
            if pos["side"] == "long":
                pos["mfe_price"] = max(pos["mfe_price"], h)
                pos["mae_price"] = min(pos["mae_price"], l)
                unreal_r = (c - pos["entry"]) / pos["risk"]
            else:
                pos["mfe_price"] = min(pos["mfe_price"], l)
                pos["mae_price"] = max(pos["mae_price"], h)
                unreal_r = (pos["entry"] - c) / pos["risk"]

            if (not pos["trail_active"]
                    and unreal_r >= params["trail_activate_r"]):
                pos["trail_active"] = True
                pos["trail_activated_epoch"] = epoch
                log(i, f"TRAIL_ACTIVATE side={pos['side']} unreal_r={unreal_r:.3f}")

            if pos["trail_active"]:
                td = params["trail_atr"] * pos["atr"]
                if pos["side"] == "long":
                    cand = c - td
                    if cand > pos["stop"]:
                        pos["stop"] = cand          # ratchets only
                else:
                    cand = c + td
                    if cand < pos["stop"]:
                        pos["stop"] = cand

            hit = (c <= pos["stop"]) if pos["side"] == "long" else (c >= pos["stop"])
            if hit:
                r = ((c - pos["entry"]) / pos["risk"] if pos["side"] == "long"
                     else (pos["entry"] - c) / pos["risk"])
                mae = ((pos["mae_price"] - pos["entry"]) / pos["risk"]
                       if pos["side"] == "long"
                       else (pos["entry"] - pos["mae_price"]) / pos["risk"])
                mfe = ((pos["mfe_price"] - pos["entry"]) / pos["risk"]
                       if pos["side"] == "long"
                       else (pos["entry"] - pos["mfe_price"]) / pos["risk"])
                trades.append({
                    "entry_epoch": pos["entry_epoch"], "exit_epoch": epoch,
                    "side": pos["side"], "entry_price": round(pos["entry"], 4),
                    "exit_price": round(c, 4), "atr_at_entry": round(pos["atr"], 6),
                    "initial_stop": round(pos["initial_stop"], 4),
                    "trail_activated_epoch": pos["trail_activated_epoch"],
                    "exit_reason": "trail" if pos["trail_active"] else "stop",
                    "r_multiple": round(r, 4), "mae_r": round(mae, 4),
                    "mfe_r": round(mfe, 4), "bars_held": pos["bars_held"],
                })
                log(i, f"EXIT side={pos['side']} r={r:.3f} "
                       f"reason={'trail' if pos['trail_active'] else 'stop'}")
                pos = None

        # ---- episode state machine -------------------------------------
        if ep_state == "inactive":
            if qualifies:
                ep_state = "active"
                ep_high, ep_low, ep_bars = h, l, 1
                episodes_started += 1
                log(i, f"EPISODE_START pct={pct:.4f}")
        elif ep_state == "active":
            if qualifies:
                ep_high = max(ep_high, h)      # qualifying bars ONLY
                ep_low = min(ep_low, l)
                ep_bars += 1
            else:
                ep_state = "frozen"
                expiry_left = params["expiry_bars"]
                log(i, f"EPISODE_FREEZE bars={ep_bars} "
                       f"range=[{ep_low:.2f},{ep_high:.2f}]")

        # ---- breakout check on frozen range ----------------------------
        if ep_state == "frozen":
            side = None
            if c > ep_high:
                side = "long"
            elif c < ep_low:
                side = "short"

            if side is not None:
                episodes_consumed += 1
                if pos is not None:
                    ignored_signals += 1
                    log(i, f"SIGNAL_IGNORED side={side} (position open)")
                else:
                    risk = params["stop_atr"] * cur
                    stop = c - risk if side == "long" else c + risk
                    pos = {
                        "entry_epoch": epoch, "entry": c, "side": side,
                        "atr": cur, "risk": risk, "initial_stop": stop,
                        "stop": stop, "trail_active": False,
                        "trail_activated_epoch": None, "bars_held": 0,
                        "mae_price": c, "mfe_price": c,
                    }
                    log(i, f"ENTRY side={side} price={c:.2f} atr={cur:.4f} "
                           f"stop={stop:.2f}")
                ep_state = "inactive"
                ep_high = ep_low = None
            else:
                expiry_left -= 1
                if expiry_left <= 0:
                    episodes_expired += 1
                    ep_state = "inactive"
                    ep_high = ep_low = None
                    log(i, "EPISODE_EXPIRED")

    # ---- unresolved position at dataset end ----------------------------
    unresolved = None
    if pos is not None:
        c = rows[-1][4]
        r = ((c - pos["entry"]) / pos["risk"] if pos["side"] == "long"
             else (pos["entry"] - c) / pos["risk"])
        unresolved = {
            "entry_epoch": pos["entry_epoch"], "side": pos["side"],
            "entry_price": round(pos["entry"], 4),
            "unrealised_r_at_boundary": round(r, 4),
            "bars_held": pos["bars_held"],
        }
        log(n - 1, f"UNRESOLVED side={pos['side']} unreal_r={r:.3f}")

    # ---- outputs -------------------------------------------------------
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    tag = "primary" if prereg_match else "exploratory"
    stem = f"phase47_{tag}_{rows[0][0]}_{rows[-1][0]}"
    trades_path = OUTPUT_DIR / f"{stem}_trades.csv"
    summary_path = OUTPUT_DIR / f"{stem}_summary.json"
    events_path = OUTPUT_DIR / f"{stem}_events.log"

    fields = ["entry_epoch", "exit_epoch", "side", "entry_price", "exit_price",
              "atr_at_entry", "initial_stop", "trail_activated_epoch",
              "exit_reason", "r_multiple", "mae_r", "mfe_r", "bars_held"]
    with open(trades_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for t in trades:
            w.writerow(t)

    with open(events_path, "w") as f:
        f.write("\n".join(events) + "\n")

    summary = {
        "phase": "47",
        "work_item": "W47.2",
        "symbol": SYMBOL,
        "granularity": GRANULARITY,
        "preregistration_match": prereg_match,
        "deviation_fields": deviations,
        "parameters": params,
        "preregistered_defaults": defaults,
        "candle_file": str(candle_path),
        "candle_sha256": _sha256(candle_path),
        "trades_sha256": _sha256(trades_path),
        "total_bars": n,
        "warmup_bars": warmup_bars,
        "evaluable_bars": max(0, n - warmup_bars),
        "first_epoch": rows[0][0],
        "last_epoch": rows[-1][0],
        "episodes_started": episodes_started,
        "episodes_consumed": episodes_consumed,
        "episodes_expired": episodes_expired,
        "ignored_signals": ignored_signals,
        "trades_closed": len(trades),
        "unresolved_trade": unresolved,
        "execution_model": "close-only, no intrabar fills",
        "known_bias": ("Close-only stop evaluation lets a bar that pierces "
                       "the stop intrabar but closes back inside survive. A "
                       "resting stop order would have filled. This likely "
                       "biases measured expectancy UPWARD versus live "
                       "execution and is NOT neutral conservatism."),
    }
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    print()
    print("-" * 68)
    print("REPLAY SUMMARY")
    for k in ("preregistration_match", "deviation_fields", "total_bars",
              "warmup_bars", "evaluable_bars", "episodes_started",
              "episodes_consumed", "episodes_expired", "ignored_signals",
              "trades_closed", "unresolved_trade", "candle_sha256",
              "trades_sha256"):
        print(f"  {k:24s}: {summary[k]}")
    print("-" * 68)
    print(f"Trades  : {trades_path}")
    print(f"Summary : {summary_path}")
    print(f"Events  : {events_path}")
    print()
    print("No metrics, expectancy, or verdict are produced here. That is W47.3.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Phase 47 compression-breakout replay (research, offline).")
    ap.add_argument("--atr-period", type=int, default=DEF_ATR_PERIOD)
    ap.add_argument("--lookback", type=int, default=DEF_LOOKBACK)
    ap.add_argument("--threshold", type=float, default=DEF_THRESHOLD)
    ap.add_argument("--stop-atr", type=float, default=DEF_STOP_ATR)
    ap.add_argument("--trail-atr", type=float, default=DEF_TRAIL_ATR)
    ap.add_argument("--trail-activate-r", type=float,
                    default=DEF_TRAIL_ACTIVATE_R)
    ap.add_argument("--expiry-bars", type=int, default=DEF_EXPIRY_BARS)
    return run(ap.parse_args())


if __name__ == "__main__":
    sys.exit(main())
